services:
  postgres:
    image: 'postgres:16'
    container_name: lms_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: learning_management_system
    ports:
      - "5433:5432"
    volumes:
      - pgdata_v16:/var/lib/postgresql/data

volumes:
  pgdata_v16:
